### ISSUE TITLE
Bug: w v1.0, links from GenMapper circles to Group are broken

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-genmapper#8]
User should be able to click a group circle in the GenMapper tool, open a dialog box (this is working), and click "Open Record" to jump directly to that Group page. Now, a 404 error message results instead.

![image](https://user-images.githubusercontent.com/47872338/107401903-5adbde80-6ad1-11eb-9eeb-7ab889a283aa.png)

![image](https://user-images.githubusercontent.com/47872338/107401939-65967380-6ad1-11eb-9037-e23ffbbe3e38.png)

![image](https://user-images.githubusercontent.com/47872338/107401960-6cbd8180-6ad1-11eb-98e4-ccbe053295df.png)

**Comment by yorkaspacher** [comment]
@corsacca or @ChrisChasm Looks like this could be a relatively simple fix - when you click the "Open Record" link, the URL it launches has "/**contacts**/{contact record number}". If you just replace "contacts" with "groups", it works perfectly.

**Comment by corsacca** [comment]
Thanks York. I confirm that the links is not working for groups.

**Comment by corsacca** [comment]
Thanks @yorkaspacher for the brilliant documentation of the issue!
V1.2 of the plugin now navigates correctly to the group record
